// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate property-bool ucd-16.0.0 --chars --include whitespace
//
// Unicode version: 16.0.0.
//
// ucd-generate 0.3.1 is available on crates.io.

public enum PerlSpace {
    public static let BY_NAME: [(String, [(Character, Character)])] =
        [("White_Space", WHITE_SPACE)]

    public static let WHITE_SPACE: [(Character, Character)] = [
        ("\t", "\r"),
        (" ", " "),
        ("\u{85}", "\u{85}"),
        ("\u{a0}", "\u{a0}"),
        ("\u{1680}", "\u{1680}"),
        ("\u{2000}", "\u{200a}"),
        ("\u{2028}", "\u{2029}"),
        ("\u{202f}", "\u{202f}"),
        ("\u{205f}", "\u{205f}"),
        ("\u{3000}", "\u{3000}"),
    ]
}
