// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate script-extension ucd-16.0.0 --chars
//
// Unicode version: 16.0.0.
//
// ucd-generate 0.3.1 is available on crates.io.

public enum ScriptExtension {
    public static let BY_NAME: [(String, [(Character, Character)])] = [
        ("Adlam", ADLAM),
        ("Ahom", AHOM),
        ("Anatolian_Hieroglyphs", ANATOLIAN_HIEROGLYPHS),
        ("Arabic", ARABIC),
        ("Armenian", ARMENIAN),
        ("Avestan", AVESTAN),
        ("Balinese", BALINESE),
        ("Bamum", BAMUM),
        ("Bassa_Vah", BASSA_VAH),
        ("Batak", BATAK),
        ("Bengali", BENGALI),
        ("Bhaiksuki", BHAIKSUKI),
        ("Bopomofo", BOPOMOFO),
        ("Brahmi", BRAHMI),
        ("Braille", BRAILLE),
        ("Buginese", BUGINESE),
        ("Buhid", BUHID),
        ("Canadian_Aboriginal", CANADIAN_ABORIGINAL),
        ("Carian", CARIAN),
        ("Caucasian_Albanian", CAUCASIAN_ALBANIAN),
        ("Chakma", CHAKMA),
        ("Cham", CHAM),
        ("Cherokee", CHEROKEE),
        ("Chorasmian", CHORASMIAN),
        ("Common", COMMON),
        ("Coptic", COPTIC),
        ("Cuneiform", CUNEIFORM),
        ("Cypriot", CYPRIOT),
        ("Cypro_Minoan", CYPRO_MINOAN),
        ("Cyrillic", CYRILLIC),
        ("Deseret", DESERET),
        ("Devanagari", DEVANAGARI),
        ("Dives_Akuru", DIVES_AKURU),
        ("Dogra", DOGRA),
        ("Duployan", DUPLOYAN),
        ("Egyptian_Hieroglyphs", EGYPTIAN_HIEROGLYPHS),
        ("Elbasan", ELBASAN),
        ("Elymaic", ELYMAIC),
        ("Ethiopic", ETHIOPIC),
        ("Garay", GARAY),
        ("Georgian", GEORGIAN),
        ("Glagolitic", GLAGOLITIC),
        ("Gothic", GOTHIC),
        ("Grantha", GRANTHA),
        ("Greek", GREEK),
        ("Gujarati", GUJARATI),
        ("Gunjala_Gondi", GUNJALA_GONDI),
        ("Gurmukhi", GURMUKHI),
        ("Gurung_Khema", GURUNG_KHEMA),
        ("Han", HAN),
        ("Hangul", HANGUL),
        ("Hanifi_Rohingya", HANIFI_ROHINGYA),
        ("Hanunoo", HANUNOO),
        ("Hatran", HATRAN),
        ("Hebrew", HEBREW),
        ("Hiragana", HIRAGANA),
        ("Imperial_Aramaic", IMPERIAL_ARAMAIC),
        ("Inherited", INHERITED),
        ("Inscriptional_Pahlavi", INSCRIPTIONAL_PAHLAVI),
        ("Inscriptional_Parthian", INSCRIPTIONAL_PARTHIAN),
        ("Javanese", JAVANESE),
        ("Kaithi", KAITHI),
        ("Kannada", KANNADA),
        ("Katakana", KATAKANA),
        ("Kawi", KAWI),
        ("Kayah_Li", KAYAH_LI),
        ("Kharoshthi", KHAROSHTHI),
        ("Khitan_Small_Script", KHITAN_SMALL_SCRIPT),
        ("Khmer", KHMER),
        ("Khojki", KHOJKI),
        ("Khudawadi", KHUDAWADI),
        ("Kirat_Rai", KIRAT_RAI),
        ("Lao", LAO),
        ("Latin", LATIN),
        ("Lepcha", LEPCHA),
        ("Limbu", LIMBU),
        ("Linear_A", LINEAR_A),
        ("Linear_B", LINEAR_B),
        ("Lisu", LISU),
        ("Lycian", LYCIAN),
        ("Lydian", LYDIAN),
        ("Mahajani", MAHAJANI),
        ("Makasar", MAKASAR),
        ("Malayalam", MALAYALAM),
        ("Mandaic", MANDAIC),
        ("Manichaean", MANICHAEAN),
        ("Marchen", MARCHEN),
        ("Masaram_Gondi", MASARAM_GONDI),
        ("Medefaidrin", MEDEFAIDRIN),
        ("Meetei_Mayek", MEETEI_MAYEK),
        ("Mende_Kikakui", MENDE_KIKAKUI),
        ("Meroitic_Cursive", MEROITIC_CURSIVE),
        ("Meroitic_Hieroglyphs", MEROITIC_HIEROGLYPHS),
        ("Miao", MIAO),
        ("Modi", MODI),
        ("Mongolian", MONGOLIAN),
        ("Mro", MRO),
        ("Multani", MULTANI),
        ("Myanmar", MYANMAR),
        ("Nabataean", NABATAEAN),
        ("Nag_Mundari", NAG_MUNDARI),
        ("Nandinagari", NANDINAGARI),
        ("New_Tai_Lue", NEW_TAI_LUE),
        ("Newa", NEWA),
        ("Nko", NKO),
        ("Nushu", NUSHU),
        ("Nyiakeng_Puachue_Hmong", NYIAKENG_PUACHUE_HMONG),
        ("Ogham", OGHAM),
        ("Ol_Chiki", OL_CHIKI),
        ("Ol_Onal", OL_ONAL),
        ("Old_Hungarian", OLD_HUNGARIAN),
        ("Old_Italic", OLD_ITALIC),
        ("Old_North_Arabian", OLD_NORTH_ARABIAN),
        ("Old_Permic", OLD_PERMIC),
        ("Old_Persian", OLD_PERSIAN),
        ("Old_Sogdian", OLD_SOGDIAN),
        ("Old_South_Arabian", OLD_SOUTH_ARABIAN),
        ("Old_Turkic", OLD_TURKIC),
        ("Old_Uyghur", OLD_UYGHUR),
        ("Oriya", ORIYA),
        ("Osage", OSAGE),
        ("Osmanya", OSMANYA),
        ("Pahawh_Hmong", PAHAWH_HMONG),
        ("Palmyrene", PALMYRENE),
        ("Pau_Cin_Hau", PAU_CIN_HAU),
        ("Phags_Pa", PHAGS_PA),
        ("Phoenician", PHOENICIAN),
        ("Psalter_Pahlavi", PSALTER_PAHLAVI),
        ("Rejang", REJANG),
        ("Runic", RUNIC),
        ("Samaritan", SAMARITAN),
        ("Saurashtra", SAURASHTRA),
        ("Sharada", SHARADA),
        ("Shavian", SHAVIAN),
        ("Siddham", SIDDHAM),
        ("SignWriting", SIGNWRITING),
        ("Sinhala", SINHALA),
        ("Sogdian", SOGDIAN),
        ("Sora_Sompeng", SORA_SOMPENG),
        ("Soyombo", SOYOMBO),
        ("Sundanese", SUNDANESE),
        ("Sunuwar", SUNUWAR),
        ("Syloti_Nagri", SYLOTI_NAGRI),
        ("Syriac", SYRIAC),
        ("Tagalog", TAGALOG),
        ("Tagbanwa", TAGBANWA),
        ("Tai_Le", TAI_LE),
        ("Tai_Tham", TAI_THAM),
        ("Tai_Viet", TAI_VIET),
        ("Takri", TAKRI),
        ("Tamil", TAMIL),
        ("Tangsa", TANGSA),
        ("Tangut", TANGUT),
        ("Telugu", TELUGU),
        ("Thaana", THAANA),
        ("Thai", THAI),
        ("Tibetan", TIBETAN),
        ("Tifinagh", TIFINAGH),
        ("Tirhuta", TIRHUTA),
        ("Todhri", TODHRI),
        ("Toto", TOTO),
        ("Tulu_Tigalari", TULU_TIGALARI),
        ("Ugaritic", UGARITIC),
        ("Vai", VAI),
        ("Vithkuqi", VITHKUQI),
        ("Wancho", WANCHO),
        ("Warang_Citi", WARANG_CITI),
        ("Yezidi", YEZIDI),
        ("Yi", YI),
        ("Zanabazar_Square", ZANABAZAR_SQUARE),
    ]

    public static let ADLAM: [(Character, Character)] = [
        ("؟", "؟"),
        ("ـ", "ـ"),
        ("⁏", "⁏"),
        ("⹁", "⹁"),
        ("𞤀", "𞥋"),
        ("𞥐", "𞥙"),
        ("𞥞", "𞥟"),
    ]

    public static let AHOM: [(Character, Character)] =
        [("𑜀", "𑜚"), ("\u{1171d}", "\u{1172b}"), ("𑜰", "𑝆")]

    public static let ANATOLIAN_HIEROGLYPHS: [(Character, Character)] = [("𔐀", "𔙆")]

    public static let ARABIC: [(Character, Character)] = [
        ("\u{600}", "\u{604}"),
        ("؆", "\u{6dc}"),
        ("۞", "ۿ"),
        ("ݐ", "ݿ"),
        ("ࡰ", "ࢎ"),
        ("\u{890}", "\u{891}"),
        ("\u{897}", "\u{8e1}"),
        ("\u{8e3}", "\u{8ff}"),
        ("⁏", "⁏"),
        ("⹁", "⹁"),
        ("ﭐ", "﯂"),
        ("ﯓ", "ﶏ"),
        ("ﶒ", "ﷇ"),
        ("﷏", "﷏"),
        ("ﷰ", "﷿"),
        ("ﹰ", "ﹴ"),
        ("ﹶ", "ﻼ"),
        ("\u{102e0}", "𐋻"),
        ("𐹠", "𐹾"),
        ("𐻂", "𐻄"),
        ("\u{10efc}", "\u{10eff}"),
        ("𞸀", "𞸃"),
        ("𞸅", "𞸟"),
        ("𞸡", "𞸢"),
        ("𞸤", "𞸤"),
        ("𞸧", "𞸧"),
        ("𞸩", "𞸲"),
        ("𞸴", "𞸷"),
        ("𞸹", "𞸹"),
        ("𞸻", "𞸻"),
        ("𞹂", "𞹂"),
        ("𞹇", "𞹇"),
        ("𞹉", "𞹉"),
        ("𞹋", "𞹋"),
        ("𞹍", "𞹏"),
        ("𞹑", "𞹒"),
        ("𞹔", "𞹔"),
        ("𞹗", "𞹗"),
        ("𞹙", "𞹙"),
        ("𞹛", "𞹛"),
        ("𞹝", "𞹝"),
        ("𞹟", "𞹟"),
        ("𞹡", "𞹢"),
        ("𞹤", "𞹤"),
        ("𞹧", "𞹪"),
        ("𞹬", "𞹲"),
        ("𞹴", "𞹷"),
        ("𞹹", "𞹼"),
        ("𞹾", "𞹾"),
        ("𞺀", "𞺉"),
        ("𞺋", "𞺛"),
        ("𞺡", "𞺣"),
        ("𞺥", "𞺩"),
        ("𞺫", "𞺻"),
        ("𞻰", "𞻱"),
    ]

    public static let ARMENIAN: [(Character, Character)] =
        [("\u{308}", "\u{308}"), ("Ա", "Ֆ"), ("ՙ", "֊"), ("֍", "֏"), ("ﬓ", "ﬗ")]

    public static let AVESTAN: [(Character, Character)] =
        [("·", "·"), ("⸰", "⸱"), ("𐬀", "𐬵"), ("𐬹", "𐬿")]

    public static let BALINESE: [(Character, Character)] = [("\u{1b00}", "ᭌ"), ("᭎", "᭿")]

    public static let BAMUM: [(Character, Character)] = [("ꚠ", "꛷"), ("𖠀", "𖨸")]

    public static let BASSA_VAH: [(Character, Character)] =
        [("𖫐", "𖫭"), ("\u{16af0}", "𖫵")]

    public static let BATAK: [(Character, Character)] = [("ᯀ", "\u{1bf3}"), ("᯼", "᯿")]

    public static let BENGALI: [(Character, Character)] = [
        ("ʼ", "ʼ"),
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("ঀ", "ঃ"),
        ("অ", "ঌ"),
        ("এ", "ঐ"),
        ("ও", "ন"),
        ("প", "র"),
        ("ল", "ল"),
        ("শ", "হ"),
        ("\u{9bc}", "\u{9c4}"),
        ("ে", "ৈ"),
        ("ো", "ৎ"),
        ("\u{9d7}", "\u{9d7}"),
        ("ড়", "ঢ়"),
        ("য়", "\u{9e3}"),
        ("০", "\u{9fe}"),
        ("\u{1cd0}", "\u{1cd0}"),
        ("\u{1cd2}", "\u{1cd2}"),
        ("\u{1cd5}", "\u{1cd6}"),
        ("\u{1cd8}", "\u{1cd8}"),
        ("᳡", "᳡"),
        ("ᳪ", "ᳪ"),
        ("\u{1ced}", "\u{1ced}"),
        ("ᳲ", "ᳲ"),
        ("ᳵ", "᳷"),
        ("\u{a8f1}", "\u{a8f1}"),
    ]

    public static let BHAIKSUKI: [(Character, Character)] =
        [("𑰀", "𑰈"), ("𑰊", "\u{11c36}"), ("\u{11c38}", "𑱅"), ("𑱐", "𑱬")]

    public static let BOPOMOFO: [(Character, Character)] = [
        ("ˇ", "ˇ"),
        ("ˉ", "ˋ"),
        ("˙", "˙"),
        ("˪", "˫"),
        ("、", "〃"),
        ("〈", "】"),
        ("〓", "〟"),
        ("\u{302a}", "\u{302d}"),
        ("〰", "〰"),
        ("〷", "〷"),
        ("・", "・"),
        ("ㄅ", "ㄯ"),
        ("ㆠ", "ㆿ"),
        ("﹅", "﹆"),
        ("｡", "･"),
    ]

    public static let BRAHMI: [(Character, Character)] =
        [("𑀀", "𑁍"), ("𑁒", "𑁵"), ("\u{1107f}", "\u{1107f}")]

    public static let BRAILLE: [(Character, Character)] = [("⠀", "⣿")]

    public static let BUGINESE: [(Character, Character)] =
        [("ᨀ", "\u{1a1b}"), ("᨞", "᨟"), ("ꧏ", "ꧏ")]

    public static let BUHID: [(Character, Character)] = [("᜵", "᜶"), ("ᝀ", "\u{1753}")]

    public static let CANADIAN_ABORIGINAL: [(Character, Character)] =
        [("᐀", "ᙿ"), ("ᢰ", "ᣵ"), ("𑪰", "𑪿")]

    public static let CARIAN: [(Character, Character)] =
        [("·", "·"), ("⁚", "⁚"), ("⁝", "⁝"), ("⸱", "⸱"), ("𐊠", "𐋐")]

    public static let CAUCASIAN_ALBANIAN: [(Character, Character)] = [
        ("\u{304}", "\u{304}"),
        ("\u{331}", "\u{331}"),
        ("\u{35e}", "\u{35e}"),
        ("𐔰", "𐕣"),
        ("𐕯", "𐕯"),
    ]

    public static let CHAKMA: [(Character, Character)] =
        [("০", "৯"), ("၀", "၉"), ("\u{11100}", "\u{11134}"), ("𑄶", "𑅇")]

    public static let CHAM: [(Character, Character)] =
        [("ꨀ", "\u{aa36}"), ("ꩀ", "ꩍ"), ("꩐", "꩙"), ("꩜", "꩟")]

    public static let CHEROKEE: [(Character, Character)] = [
        ("\u{300}", "\u{302}"),
        ("\u{304}", "\u{304}"),
        ("\u{30b}", "\u{30c}"),
        ("\u{323}", "\u{324}"),
        ("\u{330}", "\u{331}"),
        ("Ꭰ", "Ᏽ"),
        ("ᏸ", "ᏽ"),
        ("ꭰ", "ꮿ"),
    ]

    public static let CHORASMIAN: [(Character, Character)] = [("𐾰", "𐿋")]

    public static let COMMON: [(Character, Character)] = [
        ("\0", "@"),
        ("[", "`"),
        ("{", "©"),
        ("«", "¶"),
        ("¸", "¹"),
        ("»", "¿"),
        ("×", "×"),
        ("÷", "÷"),
        ("ʹ", "ʻ"),
        ("ʽ", "ˆ"),
        ("ˈ", "ˈ"),
        ("ˌ", "ˌ"),
        ("ˎ", "˖"),
        ("˘", "˘"),
        ("˚", "˟"),
        ("˥", "˩"),
        ("ˬ", "˿"),
        (";", ";"),
        ("΅", "΅"),
        ("·", "·"),
        ("\u{605}", "\u{605}"),
        ("\u{6dd}", "\u{6dd}"),
        ("\u{8e2}", "\u{8e2}"),
        ("฿", "฿"),
        ("࿕", "࿘"),
        ("\u{2000}", "\u{200b}"),
        ("\u{200e}", "\u{202e}"),
        ("‰", "⁎"),
        ("⁐", "⁙"),
        ("⁛", "⁜"),
        ("⁞", "\u{2064}"),
        ("\u{2066}", "⁰"),
        ("⁴", "⁾"),
        ("₀", "₎"),
        ("₠", "⃀"),
        ("℀", "℥"),
        ("℧", "℩"),
        ("ℬ", "ℱ"),
        ("ℳ", "⅍"),
        ("⅏", "⅟"),
        ("↉", "↋"),
        ("←", "␩"),
        ("⑀", "⑊"),
        ("①", "⟿"),
        ("⤀", "⭳"),
        ("⭶", "⮕"),
        ("⮗", "⯿"),
        ("⸀", "⸖"),
        ("⸘", "ⸯ"),
        ("⸲", "⸻"),
        ("⸽", "⹀"),
        ("⹂", "⹂"),
        ("⹄", "⹝"),
        ("\u{3000}", "\u{3000}"),
        ("〄", "〄"),
        ("〒", "〒"),
        ("〠", "〠"),
        ("〶", "〶"),
        ("㉈", "㉟"),
        ("㉿", "㉿"),
        ("㊱", "㊿"),
        ("㋌", "㋏"),
        ("㍱", "㍺"),
        ("㎀", "㏟"),
        ("㏿", "㏿"),
        ("䷀", "䷿"),
        ("꜈", "꜡"),
        ("ꞈ", "꞊"),
        ("꭛", "꭛"),
        ("꭪", "꭫"),
        ("︐", "︙"),
        ("︰", "﹄"),
        ("﹇", "﹒"),
        ("﹔", "﹦"),
        ("﹨", "﹫"),
        ("\u{feff}", "\u{feff}"),
        ("！", "＠"),
        ("［", "｀"),
        ("｛", "｠"),
        ("￠", "￦"),
        ("￨", "￮"),
        ("\u{fff9}", "�"),
        ("𐆐", "𐆜"),
        ("𐇐", "𐇼"),
        ("𜰀", "𜳹"),
        ("𜴀", "𜺳"),
        ("𜽐", "𜿃"),
        ("𝀀", "𝃵"),
        ("𝄀", "𝄦"),
        ("𝄩", "\u{1d166}"),
        ("𝅪", "\u{1d17a}"),
        ("𝆃", "𝆄"),
        ("𝆌", "𝆩"),
        ("𝆮", "𝇪"),
        ("𝋀", "𝋓"),
        ("𝋠", "𝋳"),
        ("𝌀", "𝍖"),
        ("𝍲", "𝍸"),
        ("𝐀", "𝑔"),
        ("𝑖", "𝒜"),
        ("𝒞", "𝒟"),
        ("𝒢", "𝒢"),
        ("𝒥", "𝒦"),
        ("𝒩", "𝒬"),
        ("𝒮", "𝒹"),
        ("𝒻", "𝒻"),
        ("𝒽", "𝓃"),
        ("𝓅", "𝔅"),
        ("𝔇", "𝔊"),
        ("𝔍", "𝔔"),
        ("𝔖", "𝔜"),
        ("𝔞", "𝔹"),
        ("𝔻", "𝔾"),
        ("𝕀", "𝕄"),
        ("𝕆", "𝕆"),
        ("𝕊", "𝕐"),
        ("𝕒", "𝚥"),
        ("𝚨", "𝟋"),
        ("𝟎", "𝟿"),
        ("𞱱", "𞲴"),
        ("𞴁", "𞴽"),
        ("🀀", "🀫"),
        ("🀰", "🂓"),
        ("🂠", "🂮"),
        ("🂱", "🂿"),
        ("🃁", "🃏"),
        ("🃑", "🃵"),
        ("🄀", "🆭"),
        ("🇦", "🇿"),
        ("🈁", "🈂"),
        ("🈐", "🈻"),
        ("🉀", "🉈"),
        ("🉠", "🉥"),
        ("🌀", "🛗"),
        ("🛜", "🛬"),
        ("🛰", "🛼"),
        ("🜀", "🝶"),
        ("🝻", "🟙"),
        ("🟠", "🟫"),
        ("🟰", "🟰"),
        ("🠀", "🠋"),
        ("🠐", "🡇"),
        ("🡐", "🡙"),
        ("🡠", "🢇"),
        ("🢐", "🢭"),
        ("🢰", "🢻"),
        ("🣀", "🣁"),
        ("🤀", "🩓"),
        ("🩠", "🩭"),
        ("🩰", "🩼"),
        ("🪀", "🪉"),
        ("🪏", "🫆"),
        ("🫎", "🫜"),
        ("🫟", "🫩"),
        ("🫰", "🫸"),
        ("🬀", "🮒"),
        ("🮔", "🯹"),
        ("\u{e0001}", "\u{e0001}"),
        ("\u{e0020}", "\u{e007f}"),
    ]

    public static let COPTIC: [(Character, Character)] = [
        ("·", "·"),
        ("\u{300}", "\u{300}"),
        ("\u{304}", "\u{305}"),
        ("\u{307}", "\u{307}"),
        ("ʹ", "͵"),
        ("Ϣ", "ϯ"),
        ("Ⲁ", "ⳳ"),
        ("⳹", "⳿"),
        ("⸗", "⸗"),
        ("\u{102e0}", "𐋻"),
    ]

    public static let CUNEIFORM: [(Character, Character)] =
        [("𒀀", "𒎙"), ("𒐀", "𒑮"), ("𒑰", "𒑴"), ("𒒀", "𒕃")]

    public static let CYPRIOT: [(Character, Character)] = [
        ("𐄀", "𐄂"),
        ("𐄇", "𐄳"),
        ("𐄷", "𐄿"),
        ("𐠀", "𐠅"),
        ("𐠈", "𐠈"),
        ("𐠊", "𐠵"),
        ("𐠷", "𐠸"),
        ("𐠼", "𐠼"),
        ("𐠿", "𐠿"),
    ]

    public static let CYPRO_MINOAN: [(Character, Character)] = [("𐄀", "𐄁"), ("𒾐", "𒿲")]

    public static let CYRILLIC: [(Character, Character)] = [
        ("ʼ", "ʼ"),
        ("\u{300}", "\u{302}"),
        ("\u{304}", "\u{304}"),
        ("\u{306}", "\u{306}"),
        ("\u{308}", "\u{308}"),
        ("\u{30b}", "\u{30b}"),
        ("\u{311}", "\u{311}"),
        ("Ѐ", "ԯ"),
        ("ᲀ", "ᲊ"),
        ("ᴫ", "ᴫ"),
        ("ᵸ", "ᵸ"),
        ("\u{1df8}", "\u{1df8}"),
        ("\u{2de0}", "\u{2dff}"),
        ("⹃", "⹃"),
        ("Ꙁ", "\u{a69f}"),
        ("\u{fe2e}", "\u{fe2f}"),
        ("𞀰", "𞁭"),
        ("\u{1e08f}", "\u{1e08f}"),
    ]

    public static let DESERET: [(Character, Character)] = [("𐐀", "𐑏")]

    public static let DEVANAGARI: [(Character, Character)] = [
        ("ʼ", "ʼ"),
        ("\u{900}", "\u{952}"),
        ("\u{955}", "ॿ"),
        ("\u{1cd0}", "ᳶ"),
        ("\u{1cf8}", "\u{1cf9}"),
        ("\u{20f0}", "\u{20f0}"),
        ("꠰", "꠹"),
        ("\u{a8e0}", "\u{a8ff}"),
        ("𑬀", "𑬉"),
    ]

    public static let DIVES_AKURU: [(Character, Character)] = [
        ("𑤀", "𑤆"),
        ("𑤉", "𑤉"),
        ("𑤌", "𑤓"),
        ("𑤕", "𑤖"),
        ("𑤘", "𑤵"),
        ("𑤷", "𑤸"),
        ("\u{1193b}", "𑥆"),
        ("𑥐", "𑥙"),
    ]

    public static let DOGRA: [(Character, Character)] =
        [("।", "९"), ("꠰", "꠹"), ("𑠀", "𑠻")]

    public static let DUPLOYAN: [(Character, Character)] = [
        ("·", "·"),
        ("\u{307}", "\u{308}"),
        ("\u{30a}", "\u{30a}"),
        ("\u{323}", "\u{324}"),
        ("⸼", "⸼"),
        ("𛰀", "𛱪"),
        ("𛱰", "𛱼"),
        ("𛲀", "𛲈"),
        ("𛲐", "𛲙"),
        ("𛲜", "\u{1bca3}"),
    ]

    public static let EGYPTIAN_HIEROGLYPHS: [(Character, Character)] =
        [("𓀀", "\u{13455}"), ("𓑠", "𔏺")]

    public static let ELBASAN: [(Character, Character)] =
        [("·", "·"), ("\u{305}", "\u{305}"), ("𐔀", "𐔧")]

    public static let ELYMAIC: [(Character, Character)] = [("𐿠", "𐿶")]

    public static let ETHIOPIC: [(Character, Character)] = [
        ("\u{30e}", "\u{30e}"),
        ("ሀ", "ቈ"),
        ("ቊ", "ቍ"),
        ("ቐ", "ቖ"),
        ("ቘ", "ቘ"),
        ("ቚ", "ቝ"),
        ("በ", "ኈ"),
        ("ኊ", "ኍ"),
        ("ነ", "ኰ"),
        ("ኲ", "ኵ"),
        ("ኸ", "ኾ"),
        ("ዀ", "ዀ"),
        ("ዂ", "ዅ"),
        ("ወ", "ዖ"),
        ("ዘ", "ጐ"),
        ("ጒ", "ጕ"),
        ("ጘ", "ፚ"),
        ("\u{135d}", "፼"),
        ("ᎀ", "᎙"),
        ("ⶀ", "ⶖ"),
        ("ⶠ", "ⶦ"),
        ("ⶨ", "ⶮ"),
        ("ⶰ", "ⶶ"),
        ("ⶸ", "ⶾ"),
        ("ⷀ", "ⷆ"),
        ("ⷈ", "ⷎ"),
        ("ⷐ", "ⷖ"),
        ("ⷘ", "ⷞ"),
        ("ꬁ", "ꬆ"),
        ("ꬉ", "ꬎ"),
        ("ꬑ", "ꬖ"),
        ("ꬠ", "ꬦ"),
        ("ꬨ", "ꬮ"),
        ("𞟠", "𞟦"),
        ("𞟨", "𞟫"),
        ("𞟭", "𞟮"),
        ("𞟰", "𞟾"),
    ]

    public static let GARAY: [(Character, Character)] = [
        ("،", "،"),
        ("؛", "؛"),
        ("؟", "؟"),
        ("𐵀", "𐵥"),
        ("\u{10d69}", "𐶅"),
        ("𐶎", "𐶏"),
    ]

    public static let GEORGIAN: [(Character, Character)] = [
        ("·", "·"),
        ("։", "։"),
        ("Ⴀ", "Ⴥ"),
        ("Ⴧ", "Ⴧ"),
        ("Ⴭ", "Ⴭ"),
        ("ა", "ჿ"),
        ("Ა", "Ჺ"),
        ("Ჽ", "Ჿ"),
        ("⁚", "⁚"),
        ("ⴀ", "ⴥ"),
        ("ⴧ", "ⴧ"),
        ("ⴭ", "ⴭ"),
        ("⸱", "⸱"),
    ]

    public static let GLAGOLITIC: [(Character, Character)] = [
        ("·", "·"),
        ("\u{303}", "\u{303}"),
        ("\u{305}", "\u{305}"),
        ("\u{484}", "\u{484}"),
        ("\u{487}", "\u{487}"),
        ("։", "։"),
        ("჻", "჻"),
        ("⁚", "⁚"),
        ("Ⰰ", "ⱟ"),
        ("⹃", "⹃"),
        ("\u{a66f}", "\u{a66f}"),
        ("\u{1e000}", "\u{1e006}"),
        ("\u{1e008}", "\u{1e018}"),
        ("\u{1e01b}", "\u{1e021}"),
        ("\u{1e023}", "\u{1e024}"),
        ("\u{1e026}", "\u{1e02a}"),
    ]

    public static let GOTHIC: [(Character, Character)] = [
        ("·", "·"),
        ("\u{304}", "\u{305}"),
        ("\u{308}", "\u{308}"),
        ("\u{331}", "\u{331}"),
        ("𐌰", "𐍊"),
    ]

    public static let GRANTHA: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("௦", "௳"),
        ("\u{1cd0}", "\u{1cd0}"),
        ("\u{1cd2}", "᳓"),
        ("ᳲ", "\u{1cf4}"),
        ("\u{1cf8}", "\u{1cf9}"),
        ("\u{20f0}", "\u{20f0}"),
        ("\u{11300}", "𑌃"),
        ("𑌅", "𑌌"),
        ("𑌏", "𑌐"),
        ("𑌓", "𑌨"),
        ("𑌪", "𑌰"),
        ("𑌲", "𑌳"),
        ("𑌵", "𑌹"),
        ("\u{1133b}", "𑍄"),
        ("𑍇", "𑍈"),
        ("𑍋", "\u{1134d}"),
        ("𑍐", "𑍐"),
        ("\u{11357}", "\u{11357}"),
        ("𑍝", "𑍣"),
        ("\u{11366}", "\u{1136c}"),
        ("\u{11370}", "\u{11374}"),
        ("𑿐", "𑿑"),
        ("𑿓", "𑿓"),
    ]

    public static let GREEK: [(Character, Character)] = [
        ("·", "·"),
        ("\u{300}", "\u{301}"),
        ("\u{304}", "\u{304}"),
        ("\u{306}", "\u{306}"),
        ("\u{308}", "\u{308}"),
        ("\u{313}", "\u{313}"),
        ("\u{342}", "\u{342}"),
        ("\u{345}", "\u{345}"),
        ("Ͱ", "ͷ"),
        ("ͺ", "ͽ"),
        ("Ϳ", "Ϳ"),
        ("΄", "΄"),
        ("Ά", "Ά"),
        ("Έ", "Ί"),
        ("Ό", "Ό"),
        ("Ύ", "Ρ"),
        ("Σ", "ϡ"),
        ("ϰ", "Ͽ"),
        ("ᴦ", "ᴪ"),
        ("ᵝ", "ᵡ"),
        ("ᵦ", "ᵪ"),
        ("ᶿ", "\u{1dc1}"),
        ("ἀ", "ἕ"),
        ("Ἐ", "Ἕ"),
        ("ἠ", "ὅ"),
        ("Ὀ", "Ὅ"),
        ("ὐ", "ὗ"),
        ("Ὑ", "Ὑ"),
        ("Ὓ", "Ὓ"),
        ("Ὕ", "Ὕ"),
        ("Ὗ", "ώ"),
        ("ᾀ", "ᾴ"),
        ("ᾶ", "ῄ"),
        ("ῆ", "ΐ"),
        ("ῖ", "Ί"),
        ("῝", "`"),
        ("ῲ", "ῴ"),
        ("ῶ", "῾"),
        ("⁝", "⁝"),
        ("Ω", "Ω"),
        ("ꭥ", "ꭥ"),
        ("𐅀", "𐆎"),
        ("𐆠", "𐆠"),
        ("𝈀", "𝉅"),
    ]

    public static let GUJARATI: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{a81}", "ઃ"),
        ("અ", "ઍ"),
        ("એ", "ઑ"),
        ("ઓ", "ન"),
        ("પ", "ર"),
        ("લ", "ળ"),
        ("વ", "હ"),
        ("\u{abc}", "\u{ac5}"),
        ("\u{ac7}", "ૉ"),
        ("ો", "\u{acd}"),
        ("ૐ", "ૐ"),
        ("ૠ", "\u{ae3}"),
        ("૦", "૱"),
        ("ૹ", "\u{aff}"),
        ("꠰", "꠹"),
    ]

    public static let GUNJALA_GONDI: [(Character, Character)] = [
        ("·", "·"),
        ("।", "॥"),
        ("𑵠", "𑵥"),
        ("𑵧", "𑵨"),
        ("𑵪", "𑶎"),
        ("\u{11d90}", "\u{11d91}"),
        ("𑶓", "𑶘"),
        ("𑶠", "𑶩"),
    ]

    public static let GURMUKHI: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{a01}", "ਃ"),
        ("ਅ", "ਊ"),
        ("ਏ", "ਐ"),
        ("ਓ", "ਨ"),
        ("ਪ", "ਰ"),
        ("ਲ", "ਲ਼"),
        ("ਵ", "ਸ਼"),
        ("ਸ", "ਹ"),
        ("\u{a3c}", "\u{a3c}"),
        ("ਾ", "\u{a42}"),
        ("\u{a47}", "\u{a48}"),
        ("\u{a4b}", "\u{a4d}"),
        ("\u{a51}", "\u{a51}"),
        ("ਖ਼", "ੜ"),
        ("ਫ਼", "ਫ਼"),
        ("੦", "੶"),
        ("꠰", "꠹"),
    ]

    public static let GURUNG_KHEMA: [(Character, Character)] = [("॥", "॥"), ("𖄀", "𖄹")]

    public static let HAN: [(Character, Character)] = [
        ("·", "·"),
        ("⺀", "⺙"),
        ("⺛", "⻳"),
        ("⼀", "⿕"),
        ("⿰", "⿿"),
        ("、", "〃"),
        ("々", "】"),
        ("〓", "〟"),
        ("〡", "\u{302d}"),
        ("〰", "〰"),
        ("〷", "〿"),
        ("・", "・"),
        ("㆐", "㆟"),
        ("㇀", "㇥"),
        ("㇯", "㇯"),
        ("㈠", "㉇"),
        ("㊀", "㊰"),
        ("㋀", "㋋"),
        ("㋿", "㋿"),
        ("㍘", "㍰"),
        ("㍻", "㍿"),
        ("㏠", "㏾"),
        ("㐀", "䶿"),
        ("一", "鿿"),
        ("꜀", "꜇"),
        ("豈", "舘"),
        ("並", "龎"),
        ("﹅", "﹆"),
        ("｡", "･"),
        ("𖿢", "𖿣"),
        ("\u{16ff0}", "\u{16ff1}"),
        ("𝍠", "𝍱"),
        ("🉐", "🉑"),
        ("𠀀", "𪛟"),
        ("𪜀", "𫜹"),
        ("𫝀", "𫠝"),
        ("𫠠", "𬺡"),
        ("𬺰", "𮯠"),
        ("𮯰", "𮹝"),
        ("丽", "𪘀"),
        ("𰀀", "𱍊"),
        ("𱍐", "𲎯"),
    ]

    public static let HANGUL: [(Character, Character)] = [
        ("ᄀ", "ᇿ"),
        ("、", "〃"),
        ("〈", "】"),
        ("〓", "〟"),
        ("\u{302e}", "〰"),
        ("〷", "〷"),
        ("・", "・"),
        ("ㄱ", "ㆎ"),
        ("㈀", "㈞"),
        ("㉠", "㉾"),
        ("ꥠ", "ꥼ"),
        ("가", "힣"),
        ("ힰ", "ퟆ"),
        ("ퟋ", "ퟻ"),
        ("﹅", "﹆"),
        ("｡", "･"),
        ("ﾠ", "ﾾ"),
        ("ￂ", "ￇ"),
        ("ￊ", "ￏ"),
        ("ￒ", "ￗ"),
        ("ￚ", "ￜ"),
    ]

    public static let HANIFI_ROHINGYA: [(Character, Character)] = [
        ("،", "،"),
        ("؛", "؛"),
        ("؟", "؟"),
        ("ـ", "ـ"),
        ("۔", "۔"),
        ("𐴀", "\u{10d27}"),
        ("𐴰", "𐴹"),
    ]

    public static let HANUNOO: [(Character, Character)] = [("ᜠ", "᜶")]

    public static let HATRAN: [(Character, Character)] =
        [("𐣠", "𐣲"), ("𐣴", "𐣵"), ("𐣻", "𐣿")]

    public static let HEBREW: [(Character, Character)] = [
        ("\u{307}", "\u{308}"),
        ("\u{591}", "\u{5c7}"),
        ("א", "ת"),
        ("ׯ", "״"),
        ("יִ", "זּ"),
        ("טּ", "לּ"),
        ("מּ", "מּ"),
        ("נּ", "סּ"),
        ("ףּ", "פּ"),
        ("צּ", "ﭏ"),
    ]

    public static let HIRAGANA: [(Character, Character)] = [
        ("、", "〃"),
        ("〈", "】"),
        ("〓", "〟"),
        ("〰", "〵"),
        ("〷", "〷"),
        ("〼", "〽"),
        ("ぁ", "ゖ"),
        ("\u{3099}", "゠"),
        ("・", "ー"),
        ("﹅", "﹆"),
        ("｡", "･"),
        ("ｰ", "ｰ"),
        ("\u{ff9e}", "\u{ff9f}"),
        ("𛀁", "𛄟"),
        ("𛄲", "𛄲"),
        ("𛅐", "𛅒"),
        ("🈀", "🈀"),
    ]

    public static let IMPERIAL_ARAMAIC: [(Character, Character)] =
        [("𐡀", "𐡕"), ("𐡗", "𐡟")]

    public static let INHERITED: [(Character, Character)] = [
        ("\u{30f}", "\u{30f}"),
        ("\u{312}", "\u{312}"),
        ("\u{314}", "\u{31f}"),
        ("\u{321}", "\u{322}"),
        ("\u{326}", "\u{32c}"),
        ("\u{32f}", "\u{32f}"),
        ("\u{332}", "\u{341}"),
        ("\u{343}", "\u{344}"),
        ("\u{346}", "\u{357}"),
        ("\u{359}", "\u{35d}"),
        ("\u{35f}", "\u{362}"),
        ("\u{953}", "\u{954}"),
        ("\u{1ab0}", "\u{1ace}"),
        ("\u{1dc2}", "\u{1df7}"),
        ("\u{1df9}", "\u{1df9}"),
        ("\u{1dfb}", "\u{1dff}"),
        ("\u{200c}", "\u{200d}"),
        ("\u{20d0}", "\u{20ef}"),
        ("\u{fe00}", "\u{fe0f}"),
        ("\u{fe20}", "\u{fe2d}"),
        ("\u{101fd}", "\u{101fd}"),
        ("\u{1cf00}", "\u{1cf2d}"),
        ("\u{1cf30}", "\u{1cf46}"),
        ("\u{1d167}", "\u{1d169}"),
        ("\u{1d17b}", "\u{1d182}"),
        ("\u{1d185}", "\u{1d18b}"),
        ("\u{1d1aa}", "\u{1d1ad}"),
        ("\u{e0100}", "\u{e01ef}"),
    ]

    public static let INSCRIPTIONAL_PAHLAVI: [(Character, Character)] =
        [("𐭠", "𐭲"), ("𐭸", "𐭿")]

    public static let INSCRIPTIONAL_PARTHIAN: [(Character, Character)] =
        [("𐭀", "𐭕"), ("𐭘", "𐭟")]

    public static let JAVANESE: [(Character, Character)] =
        [("\u{a980}", "꧍"), ("ꧏ", "꧙"), ("꧞", "꧟")]

    public static let KAITHI: [(Character, Character)] = [
        ("०", "९"),
        ("⸱", "⸱"),
        ("꠰", "꠹"),
        ("\u{11080}", "\u{110c2}"),
        ("\u{110cd}", "\u{110cd}"),
    ]

    public static let KANNADA: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("ಀ", "ಌ"),
        ("ಎ", "ಐ"),
        ("ಒ", "ನ"),
        ("ಪ", "ಳ"),
        ("ವ", "ಹ"),
        ("\u{cbc}", "ೄ"),
        ("\u{cc6}", "\u{cc8}"),
        ("\u{cca}", "\u{ccd}"),
        ("\u{cd5}", "\u{cd6}"),
        ("ೝ", "ೞ"),
        ("ೠ", "\u{ce3}"),
        ("೦", "೯"),
        ("ೱ", "ೳ"),
        ("\u{1cd0}", "\u{1cd0}"),
        ("\u{1cd2}", "᳓"),
        ("\u{1cda}", "\u{1cda}"),
        ("ᳲ", "ᳲ"),
        ("\u{1cf4}", "\u{1cf4}"),
        ("꠰", "꠵"),
    ]

    public static let KATAKANA: [(Character, Character)] = [
        ("\u{305}", "\u{305}"),
        ("\u{323}", "\u{323}"),
        ("、", "〃"),
        ("〈", "】"),
        ("〓", "〟"),
        ("〰", "〵"),
        ("〷", "〷"),
        ("〼", "〽"),
        ("\u{3099}", "゜"),
        ("゠", "ヿ"),
        ("ㇰ", "ㇿ"),
        ("㋐", "㋾"),
        ("㌀", "㍗"),
        ("﹅", "﹆"),
        ("｡", "\u{ff9f}"),
        ("𚿰", "𚿳"),
        ("𚿵", "𚿻"),
        ("𚿽", "𚿾"),
        ("𛀀", "𛀀"),
        ("𛄠", "𛄢"),
        ("𛅕", "𛅕"),
        ("𛅤", "𛅧"),
    ]

    public static let KAWI: [(Character, Character)] =
        [("\u{11f00}", "𑼐"), ("𑼒", "\u{11f3a}"), ("𑼾", "\u{11f5a}")]

    public static let KAYAH_LI: [(Character, Character)] = [("꤀", "꤯")]

    public static let KHAROSHTHI: [(Character, Character)] = [
        ("𐨀", "\u{10a03}"),
        ("\u{10a05}", "\u{10a06}"),
        ("\u{10a0c}", "𐨓"),
        ("𐨕", "𐨗"),
        ("𐨙", "𐨵"),
        ("\u{10a38}", "\u{10a3a}"),
        ("\u{10a3f}", "𐩈"),
        ("𐩐", "𐩘"),
    ]

    public static let KHITAN_SMALL_SCRIPT: [(Character, Character)] =
        [("\u{16fe4}", "\u{16fe4}"), ("𘬀", "𘳕"), ("𘳿", "𘳿")]

    public static let KHMER: [(Character, Character)] =
        [("ក", "\u{17dd}"), ("០", "៩"), ("៰", "៹"), ("᧠", "᧿")]

    public static let KHOJKI: [(Character, Character)] =
        [("૦", "૯"), ("꠰", "꠹"), ("𑈀", "𑈑"), ("𑈓", "\u{11241}")]

    public static let KHUDAWADI: [(Character, Character)] =
        [("।", "॥"), ("꠰", "꠹"), ("𑊰", "\u{112ea}"), ("𑋰", "𑋹")]

    public static let KIRAT_RAI: [(Character, Character)] = [("𖵀", "𖵹")]

    public static let LAO: [(Character, Character)] = [
        ("ກ", "ຂ"),
        ("ຄ", "ຄ"),
        ("ຆ", "ຊ"),
        ("ຌ", "ຣ"),
        ("ລ", "ລ"),
        ("ວ", "ຽ"),
        ("ເ", "ໄ"),
        ("ໆ", "ໆ"),
        ("\u{ec8}", "\u{ece}"),
        ("໐", "໙"),
        ("ໜ", "ໟ"),
    ]

    public static let LATIN: [(Character, Character)] = [
        ("A", "Z"),
        ("a", "z"),
        ("ª", "ª"),
        ("·", "·"),
        ("º", "º"),
        ("À", "Ö"),
        ("Ø", "ö"),
        ("ø", "ʸ"),
        ("ʼ", "ʼ"),
        ("ˇ", "ˇ"),
        ("ˉ", "ˋ"),
        ("ˍ", "ˍ"),
        ("˗", "˗"),
        ("˙", "˙"),
        ("ˠ", "ˤ"),
        ("\u{300}", "\u{30e}"),
        ("\u{310}", "\u{311}"),
        ("\u{313}", "\u{313}"),
        ("\u{320}", "\u{320}"),
        ("\u{323}", "\u{325}"),
        ("\u{32d}", "\u{32e}"),
        ("\u{330}", "\u{331}"),
        ("\u{358}", "\u{358}"),
        ("\u{35e}", "\u{35e}"),
        ("\u{363}", "\u{36f}"),
        ("\u{485}", "\u{486}"),
        ("\u{951}", "\u{952}"),
        ("჻", "჻"),
        ("ᴀ", "ᴥ"),
        ("ᴬ", "ᵜ"),
        ("ᵢ", "ᵥ"),
        ("ᵫ", "ᵷ"),
        ("ᵹ", "ᶾ"),
        ("\u{1df8}", "\u{1df8}"),
        ("Ḁ", "ỿ"),
        ("\u{202f}", "\u{202f}"),
        ("ⁱ", "ⁱ"),
        ("ⁿ", "ⁿ"),
        ("ₐ", "ₜ"),
        ("\u{20f0}", "\u{20f0}"),
        ("K", "Å"),
        ("Ⅎ", "Ⅎ"),
        ("ⅎ", "ⅎ"),
        ("Ⅰ", "ↈ"),
        ("Ⱡ", "Ɀ"),
        ("⸗", "⸗"),
        ("꜀", "꜇"),
        ("Ꜣ", "ꞇ"),
        ("Ꞌ", "ꟍ"),
        ("Ꟑ", "ꟑ"),
        ("ꟓ", "ꟓ"),
        ("ꟕ", "Ƛ"),
        ("ꟲ", "ꟿ"),
        ("꤮", "꤮"),
        ("ꬰ", "ꭚ"),
        ("ꭜ", "ꭤ"),
        ("ꭦ", "ꭩ"),
        ("ﬀ", "ﬆ"),
        ("Ａ", "Ｚ"),
        ("ａ", "ｚ"),
        ("𐞀", "𐞅"),
        ("𐞇", "𐞰"),
        ("𐞲", "𐞺"),
        ("𝼀", "𝼞"),
        ("𝼥", "𝼪"),
    ]

    public static let LEPCHA: [(Character, Character)] =
        [("ᰀ", "\u{1c37}"), ("᰻", "᱉"), ("ᱍ", "ᱏ")]

    public static let LIMBU: [(Character, Character)] = [
        ("॥", "॥"),
        ("ᤀ", "ᤞ"),
        ("\u{1920}", "ᤫ"),
        ("ᤰ", "\u{193b}"),
        ("᥀", "᥀"),
        ("᥄", "᥏"),
    ]

    public static let LINEAR_A: [(Character, Character)] =
        [("𐄇", "𐄳"), ("𐘀", "𐜶"), ("𐝀", "𐝕"), ("𐝠", "𐝧")]

    public static let LINEAR_B: [(Character, Character)] = [
        ("𐀀", "𐀋"),
        ("𐀍", "𐀦"),
        ("𐀨", "𐀺"),
        ("𐀼", "𐀽"),
        ("𐀿", "𐁍"),
        ("𐁐", "𐁝"),
        ("𐂀", "𐃺"),
        ("𐄀", "𐄂"),
        ("𐄇", "𐄳"),
        ("𐄷", "𐄿"),
    ]

    public static let LISU: [(Character, Character)] =
        [("ʼ", "ʼ"), ("ˍ", "ˍ"), ("《", "》"), ("ꓐ", "꓿"), ("𑾰", "𑾰")]

    public static let LYCIAN: [(Character, Character)] = [("⁚", "⁚"), ("𐊀", "𐊜")]

    public static let LYDIAN: [(Character, Character)] =
        [("·", "·"), ("⸱", "⸱"), ("𐤠", "𐤹"), ("𐤿", "𐤿")]

    public static let MAHAJANI: [(Character, Character)] =
        [("·", "·"), ("।", "९"), ("꠰", "꠹"), ("𑅐", "𑅶")]

    public static let MAKASAR: [(Character, Character)] = [("𑻠", "𑻸")]

    public static let MALAYALAM: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{d00}", "ഌ"),
        ("എ", "ഐ"),
        ("ഒ", "\u{d44}"),
        ("െ", "ൈ"),
        ("ൊ", "൏"),
        ("ൔ", "\u{d63}"),
        ("൦", "ൿ"),
        ("\u{1cda}", "\u{1cda}"),
        ("ᳲ", "ᳲ"),
        ("꠰", "꠲"),
    ]

    public static let MANDAIC: [(Character, Character)] =
        [("ـ", "ـ"), ("ࡀ", "\u{85b}"), ("࡞", "࡞")]

    public static let MANICHAEAN: [(Character, Character)] =
        [("ـ", "ـ"), ("𐫀", "\u{10ae6}"), ("𐫫", "𐫶")]

    public static let MARCHEN: [(Character, Character)] =
        [("𑱰", "𑲏"), ("\u{11c92}", "\u{11ca7}"), ("𑲩", "\u{11cb6}")]

    public static let MASARAM_GONDI: [(Character, Character)] = [
        ("।", "॥"),
        ("𑴀", "𑴆"),
        ("𑴈", "𑴉"),
        ("𑴋", "\u{11d36}"),
        ("\u{11d3a}", "\u{11d3a}"),
        ("\u{11d3c}", "\u{11d3d}"),
        ("\u{11d3f}", "\u{11d47}"),
        ("𑵐", "𑵙"),
    ]

    public static let MEDEFAIDRIN: [(Character, Character)] = [("𖹀", "𖺚")]

    public static let MEETEI_MAYEK: [(Character, Character)] =
        [("ꫠ", "\u{aaf6}"), ("ꯀ", "\u{abed}"), ("꯰", "꯹")]

    public static let MENDE_KIKAKUI: [(Character, Character)] =
        [("𞠀", "𞣄"), ("𞣇", "\u{1e8d6}")]

    public static let MEROITIC_CURSIVE: [(Character, Character)] =
        [("𐦠", "𐦷"), ("𐦼", "𐧏"), ("𐧒", "𐧿")]

    public static let MEROITIC_HIEROGLYPHS: [(Character, Character)] =
        [("⁝", "⁝"), ("𐦀", "𐦟")]

    public static let MIAO: [(Character, Character)] =
        [("𖼀", "𖽊"), ("\u{16f4f}", "𖾇"), ("\u{16f8f}", "𖾟")]

    public static let MODI: [(Character, Character)] =
        [("꠰", "꠹"), ("𑘀", "𑙄"), ("𑙐", "𑙙")]

    public static let MONGOLIAN: [(Character, Character)] = [
        ("᠀", "᠙"),
        ("ᠠ", "ᡸ"),
        ("ᢀ", "ᢪ"),
        ("\u{202f}", "\u{202f}"),
        ("、", "。"),
        ("〈", "》"),
        ("𑙠", "𑙬"),
    ]

    public static let MRO: [(Character, Character)] = [("𖩀", "𖩞"), ("𖩠", "𖩩"), ("𖩮", "𖩯")]

    public static let MULTANI: [(Character, Character)] =
        [("੦", "੯"), ("𑊀", "𑊆"), ("𑊈", "𑊈"), ("𑊊", "𑊍"), ("𑊏", "𑊝"), ("𑊟", "𑊩")]

    public static let MYANMAR: [(Character, Character)] =
        [("က", "႟"), ("꤮", "꤮"), ("ꧠ", "ꧾ"), ("ꩠ", "ꩿ"), ("𑛐", "𑛣")]

    public static let NABATAEAN: [(Character, Character)] = [("𐢀", "𐢞"), ("𐢧", "𐢯")]

    public static let NAG_MUNDARI: [(Character, Character)] = [("𞓐", "𞓹")]

    public static let NANDINAGARI: [(Character, Character)] = [
        ("।", "॥"),
        ("೦", "೯"),
        ("ᳩ", "ᳩ"),
        ("ᳲ", "ᳲ"),
        ("ᳺ", "ᳺ"),
        ("꠰", "꠵"),
        ("𑦠", "𑦧"),
        ("𑦪", "\u{119d7}"),
        ("\u{119da}", "𑧤"),
    ]

    public static let NEW_TAI_LUE: [(Character, Character)] =
        [("ᦀ", "ᦫ"), ("ᦰ", "ᧉ"), ("᧐", "᧚"), ("᧞", "᧟")]

    public static let NEWA: [(Character, Character)] = [("𑐀", "𑑛"), ("𑑝", "𑑡")]

    public static let NKO: [(Character, Character)] = [
        ("،", "،"),
        ("؛", "؛"),
        ("؟", "؟"),
        ("߀", "ߺ"),
        ("\u{7fd}", "߿"),
        ("﴾", "﴿"),
    ]

    public static let NUSHU: [(Character, Character)] = [("𖿡", "𖿡"), ("𛅰", "𛋻")]

    public static let NYIAKENG_PUACHUE_HMONG: [(Character, Character)] =
        [("𞄀", "𞄬"), ("\u{1e130}", "𞄽"), ("𞅀", "𞅉"), ("𞅎", "𞅏")]

    public static let OGHAM: [(Character, Character)] = [("\u{1680}", "᚜")]

    public static let OL_CHIKI: [(Character, Character)] = [("᱐", "᱿")]

    public static let OL_ONAL: [(Character, Character)] =
        [("।", "॥"), ("𞗐", "𞗺"), ("𞗿", "𞗿")]

    public static let OLD_HUNGARIAN: [(Character, Character)] = [
        ("⁚", "⁚"),
        ("⁝", "⁝"),
        ("⸱", "⸱"),
        ("⹁", "⹁"),
        ("𐲀", "𐲲"),
        ("𐳀", "𐳲"),
        ("𐳺", "𐳿"),
    ]

    public static let OLD_ITALIC: [(Character, Character)] = [("𐌀", "𐌣"), ("𐌭", "𐌯")]

    public static let OLD_NORTH_ARABIAN: [(Character, Character)] = [("𐪀", "𐪟")]

    public static let OLD_PERMIC: [(Character, Character)] = [
        ("·", "·"),
        ("\u{300}", "\u{300}"),
        ("\u{306}", "\u{308}"),
        ("\u{313}", "\u{313}"),
        ("\u{483}", "\u{483}"),
        ("𐍐", "\u{1037a}"),
    ]

    public static let OLD_PERSIAN: [(Character, Character)] = [("𐎠", "𐏃"), ("𐏈", "𐏕")]

    public static let OLD_SOGDIAN: [(Character, Character)] = [("𐼀", "𐼧")]

    public static let OLD_SOUTH_ARABIAN: [(Character, Character)] = [("𐩠", "𐩿")]

    public static let OLD_TURKIC: [(Character, Character)] =
        [("⁚", "⁚"), ("⸰", "⸰"), ("𐰀", "𐱈")]

    public static let OLD_UYGHUR: [(Character, Character)] =
        [("ـ", "ـ"), ("𐫲", "𐫲"), ("𐽰", "𐾉")]

    public static let ORIYA: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{b01}", "ଃ"),
        ("ଅ", "ଌ"),
        ("ଏ", "ଐ"),
        ("ଓ", "ନ"),
        ("ପ", "ର"),
        ("ଲ", "ଳ"),
        ("ଵ", "ହ"),
        ("\u{b3c}", "\u{b44}"),
        ("େ", "ୈ"),
        ("ୋ", "\u{b4d}"),
        ("\u{b55}", "\u{b57}"),
        ("ଡ଼", "ଢ଼"),
        ("ୟ", "\u{b63}"),
        ("୦", "୷"),
        ("\u{1cda}", "\u{1cda}"),
        ("ᳲ", "ᳲ"),
    ]

    public static let OSAGE: [(Character, Character)] = [
        ("\u{301}", "\u{301}"),
        ("\u{304}", "\u{304}"),
        ("\u{30b}", "\u{30b}"),
        ("\u{358}", "\u{358}"),
        ("𐒰", "𐓓"),
        ("𐓘", "𐓻"),
    ]

    public static let OSMANYA: [(Character, Character)] = [("𐒀", "𐒝"), ("𐒠", "𐒩")]

    public static let PAHAWH_HMONG: [(Character, Character)] =
        [("𖬀", "𖭅"), ("𖭐", "𖭙"), ("𖭛", "𖭡"), ("𖭣", "𖭷"), ("𖭽", "𖮏")]

    public static let PALMYRENE: [(Character, Character)] = [("𐡠", "𐡿")]

    public static let PAU_CIN_HAU: [(Character, Character)] = [("𑫀", "𑫸")]

    public static let PHAGS_PA: [(Character, Character)] = [
        ("᠂", "᠃"),
        ("᠅", "᠅"),
        ("\u{202f}", "\u{202f}"),
        ("。", "。"),
        ("ꡀ", "꡷"),
    ]

    public static let PHOENICIAN: [(Character, Character)] = [("𐤀", "𐤛"), ("𐤟", "𐤟")]

    public static let PSALTER_PAHLAVI: [(Character, Character)] =
        [("ـ", "ـ"), ("𐮀", "𐮑"), ("𐮙", "𐮜"), ("𐮩", "𐮯")]

    public static let REJANG: [(Character, Character)] = [("ꤰ", "\u{a953}"), ("꥟", "꥟")]

    public static let RUNIC: [(Character, Character)] = [("ᚠ", "ᛸ")]

    public static let SAMARITAN: [(Character, Character)] =
        [("ࠀ", "\u{82d}"), ("࠰", "࠾"), ("⸱", "⸱")]

    public static let SAURASHTRA: [(Character, Character)] =
        [("ꢀ", "\u{a8c5}"), ("꣎", "꣙")]

    public static let SHARADA: [(Character, Character)] = [
        ("\u{951}", "\u{951}"),
        ("\u{1cd7}", "\u{1cd7}"),
        ("\u{1cd9}", "\u{1cd9}"),
        ("\u{1cdc}", "\u{1cdd}"),
        ("\u{1ce0}", "\u{1ce0}"),
        ("꠰", "꠵"),
        ("꠸", "꠸"),
        ("\u{11180}", "𑇟"),
    ]

    public static let SHAVIAN: [(Character, Character)] = [("·", "·"), ("𐑐", "𐑿")]

    public static let SIDDHAM: [(Character, Character)] =
        [("𑖀", "\u{115b5}"), ("𑖸", "\u{115dd}")]

    public static let SIGNWRITING: [(Character, Character)] =
        [("𝠀", "𝪋"), ("\u{1da9b}", "\u{1da9f}"), ("\u{1daa1}", "\u{1daaf}")]

    public static let SINHALA: [(Character, Character)] = [
        ("।", "॥"),
        ("\u{d81}", "ඃ"),
        ("අ", "ඖ"),
        ("ක", "න"),
        ("ඳ", "ර"),
        ("ල", "ල"),
        ("ව", "ෆ"),
        ("\u{dca}", "\u{dca}"),
        ("\u{dcf}", "\u{dd4}"),
        ("\u{dd6}", "\u{dd6}"),
        ("ෘ", "\u{ddf}"),
        ("෦", "෯"),
        ("ෲ", "෴"),
        ("ᳲ", "ᳲ"),
        ("𑇡", "𑇴"),
    ]

    public static let SOGDIAN: [(Character, Character)] = [("ـ", "ـ"), ("𐼰", "𐽙")]

    public static let SORA_SOMPENG: [(Character, Character)] = [("𑃐", "𑃨"), ("𑃰", "𑃹")]

    public static let SOYOMBO: [(Character, Character)] = [("𑩐", "𑪢")]

    public static let SUNDANESE: [(Character, Character)] =
        [("\u{1b80}", "ᮿ"), ("᳀", "᳇")]

    public static let SUNUWAR: [(Character, Character)] = [
        ("\u{300}", "\u{301}"),
        ("\u{303}", "\u{303}"),
        ("\u{30d}", "\u{30d}"),
        ("\u{310}", "\u{310}"),
        ("\u{32d}", "\u{32d}"),
        ("\u{331}", "\u{331}"),
        ("𑯀", "𑯡"),
        ("𑯰", "𑯹"),
    ]

    public static let SYLOTI_NAGRI: [(Character, Character)] =
        [("।", "॥"), ("০", "৯"), ("ꠀ", "\u{a82c}")]

    public static let SYRIAC: [(Character, Character)] = [
        ("\u{303}", "\u{304}"),
        ("\u{307}", "\u{308}"),
        ("\u{30a}", "\u{30a}"),
        ("\u{320}", "\u{320}"),
        ("\u{323}", "\u{325}"),
        ("\u{32d}", "\u{32e}"),
        ("\u{330}", "\u{330}"),
        ("،", "،"),
        ("؛", "\u{61c}"),
        ("؟", "؟"),
        ("ـ", "ـ"),
        ("\u{64b}", "\u{655}"),
        ("\u{670}", "\u{670}"),
        ("܀", "܍"),
        ("\u{70f}", "\u{74a}"),
        ("ݍ", "ݏ"),
        ("ࡠ", "ࡪ"),
        ("\u{1df8}", "\u{1df8}"),
        ("\u{1dfa}", "\u{1dfa}"),
    ]

    public static let TAGALOG: [(Character, Character)] =
        [("ᜀ", "\u{1715}"), ("ᜟ", "ᜟ"), ("᜵", "᜶")]

    public static let TAGBANWA: [(Character, Character)] =
        [("᜵", "᜶"), ("ᝠ", "ᝬ"), ("ᝮ", "ᝰ"), ("\u{1772}", "\u{1773}")]

    public static let TAI_LE: [(Character, Character)] = [
        ("\u{300}", "\u{301}"),
        ("\u{307}", "\u{308}"),
        ("\u{30c}", "\u{30c}"),
        ("၀", "၉"),
        ("ᥐ", "ᥭ"),
        ("ᥰ", "ᥴ"),
    ]

    public static let TAI_THAM: [(Character, Character)] = [
        ("ᨠ", "\u{1a5e}"),
        ("\u{1a60}", "\u{1a7c}"),
        ("\u{1a7f}", "᪉"),
        ("᪐", "᪙"),
        ("᪠", "᪭"),
    ]

    public static let TAI_VIET: [(Character, Character)] = [("ꪀ", "ꫂ"), ("ꫛ", "꫟")]

    public static let TAKRI: [(Character, Character)] =
        [("।", "॥"), ("꠰", "꠹"), ("𑚀", "𑚹"), ("𑛀", "𑛉")]

    public static let TAMIL: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{b82}", "ஃ"),
        ("அ", "ஊ"),
        ("எ", "ஐ"),
        ("ஒ", "க"),
        ("ங", "ச"),
        ("ஜ", "ஜ"),
        ("ஞ", "ட"),
        ("ண", "த"),
        ("ந", "ப"),
        ("ம", "ஹ"),
        ("\u{bbe}", "ூ"),
        ("ெ", "ை"),
        ("ொ", "\u{bcd}"),
        ("ௐ", "ௐ"),
        ("\u{bd7}", "\u{bd7}"),
        ("௦", "௺"),
        ("\u{1cda}", "\u{1cda}"),
        ("ꣳ", "ꣳ"),
        ("\u{11301}", "\u{11301}"),
        ("𑌃", "𑌃"),
        ("\u{1133b}", "\u{1133c}"),
        ("𑿀", "𑿱"),
        ("𑿿", "𑿿"),
    ]

    public static let TANGSA: [(Character, Character)] = [("𖩰", "𖪾"), ("𖫀", "𖫉")]

    public static let TANGUT: [(Character, Character)] = [
        ("⿰", "⿿"),
        ("㇯", "㇯"),
        ("𖿠", "𖿠"),
        ("𗀀", "𘟷"),
        ("𘠀", "𘫿"),
        ("𘴀", "𘴈"),
    ]

    public static let TELUGU: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("\u{c00}", "ఌ"),
        ("ఎ", "ఐ"),
        ("ఒ", "న"),
        ("ప", "హ"),
        ("\u{c3c}", "ౄ"),
        ("\u{c46}", "\u{c48}"),
        ("\u{c4a}", "\u{c4d}"),
        ("\u{c55}", "\u{c56}"),
        ("ౘ", "ౚ"),
        ("ౝ", "ౝ"),
        ("ౠ", "\u{c63}"),
        ("౦", "౯"),
        ("౷", "౿"),
        ("\u{1cda}", "\u{1cda}"),
        ("ᳲ", "ᳲ"),
    ]

    public static let THAANA: [(Character, Character)] = [
        ("،", "،"),
        ("؛", "\u{61c}"),
        ("؟", "؟"),
        ("٠", "٩"),
        ("ހ", "ޱ"),
        ("ﷲ", "ﷲ"),
        ("﷽", "﷽"),
    ]

    public static let THAI: [(Character, Character)] = [
        ("ʼ", "ʼ"),
        ("˗", "˗"),
        ("\u{303}", "\u{303}"),
        ("\u{331}", "\u{331}"),
        ("ก", "\u{e3a}"),
        ("เ", "๛"),
    ]

    public static let TIBETAN: [(Character, Character)] = [
        ("ༀ", "ཇ"),
        ("ཉ", "ཬ"),
        ("\u{f71}", "\u{f97}"),
        ("\u{f99}", "\u{fbc}"),
        ("྾", "࿌"),
        ("࿎", "࿔"),
        ("࿙", "࿚"),
        ("〈", "》"),
    ]

    public static let TIFINAGH: [(Character, Character)] = [
        ("\u{302}", "\u{302}"),
        ("\u{304}", "\u{304}"),
        ("\u{307}", "\u{307}"),
        ("\u{309}", "\u{309}"),
        ("ⴰ", "ⵧ"),
        ("ⵯ", "⵰"),
        ("\u{2d7f}", "\u{2d7f}"),
    ]

    public static let TIRHUTA: [(Character, Character)] = [
        ("\u{951}", "\u{952}"),
        ("।", "॥"),
        ("ᳲ", "ᳲ"),
        ("꠰", "꠹"),
        ("𑒀", "𑓇"),
        ("𑓐", "𑓙"),
    ]

    public static let TODHRI: [(Character, Character)] = [
        ("\u{301}", "\u{301}"),
        ("\u{304}", "\u{304}"),
        ("\u{307}", "\u{307}"),
        ("\u{311}", "\u{311}"),
        ("\u{313}", "\u{313}"),
        ("\u{35e}", "\u{35e}"),
        ("𐗀", "𐗳"),
    ]

    public static let TOTO: [(Character, Character)] = [("ʼ", "ʼ"), ("𞊐", "\u{1e2ae}")]

    public static let TULU_TIGALARI: [(Character, Character)] = [
        ("೦", "೯"),
        ("ᳲ", "ᳲ"),
        ("\u{1cf4}", "\u{1cf4}"),
        ("꠰", "꠵"),
        ("\u{a8f1}", "\u{a8f1}"),
        ("𑎀", "𑎉"),
        ("𑎋", "𑎋"),
        ("𑎎", "𑎎"),
        ("𑎐", "𑎵"),
        ("𑎷", "\u{113c0}"),
        ("\u{113c2}", "\u{113c2}"),
        ("\u{113c5}", "\u{113c5}"),
        ("\u{113c7}", "𑏊"),
        ("𑏌", "𑏕"),
        ("𑏗", "𑏘"),
        ("\u{113e1}", "\u{113e2}"),
    ]

    public static let UGARITIC: [(Character, Character)] = [("𐎀", "𐎝"), ("𐎟", "𐎟")]

    public static let VAI: [(Character, Character)] = [("ꔀ", "ꘫ")]

    public static let VITHKUQI: [(Character, Character)] = [
        ("𐕰", "𐕺"),
        ("𐕼", "𐖊"),
        ("𐖌", "𐖒"),
        ("𐖔", "𐖕"),
        ("𐖗", "𐖡"),
        ("𐖣", "𐖱"),
        ("𐖳", "𐖹"),
        ("𐖻", "𐖼"),
    ]

    public static let WANCHO: [(Character, Character)] = [("𞋀", "𞋹"), ("𞋿", "𞋿")]

    public static let WARANG_CITI: [(Character, Character)] = [("𑢠", "𑣲"), ("𑣿", "𑣿")]

    public static let YEZIDI: [(Character, Character)] = [
        ("،", "،"),
        ("؛", "؛"),
        ("؟", "؟"),
        ("٠", "٩"),
        ("𐺀", "𐺩"),
        ("\u{10eab}", "𐺭"),
        ("𐺰", "𐺱"),
    ]

    public static let YI: [(Character, Character)] = [
        ("、", "。"),
        ("〈", "】"),
        ("〔", "〛"),
        ("・", "・"),
        ("ꀀ", "ꒌ"),
        ("꒐", "꓆"),
        ("｡", "･"),
    ]

    public static let ZANABAZAR_SQUARE: [(Character, Character)] = [("𑨀", "\u{11a47}")]
}
